# Refer to roles/gitlab/defaults/main.yml for more explanation

gitlab_external_url: http://gitlab.example.com
gitlab_access_token: 'glpat-sfstJUmFHRHvuaaouQ9Y'

gitlab_puma_worker_processes: 4

# See https://docs.gitlab.com/ee/administration/auth/ldap/ for config example
gitlab_ldap_enabled: true
gitlab_ldap_host: 'ldap.forumsys.com'
gitlab_ldap_port: 389
gitlab_ldap_uid: uid
gitlab_ldap_encryption: plain
gitlab_ldap_bind_dn: 'cn=read-only-admin,dc=example,dc=com'
gitlab_ldap_bind_password: 'password'
gitlab_ldap_tls_ca_file: ''
gitlab_ldap_tls_ssl_version: ''
gitlab_ldap_ciphers: ''
gitlab_ldap_tls_cert: ''
gitlab_ldap_tls_key: ''
gitlab_ldap_active_directory: false
gitlab_ldap_allow_username_or_email_login: true
gitlab_ldap_block_auto_created_users: false
gitlab_ldap_base: 'dc=example,dc=com'
gitlab_ldap_user_filter: ''
gitlab_ldap_attributes_username: "'uid'"
gitlab_ldap_attributes_email: "'mail', 'email', 'userPrincipalName'"
gitlab_ldap_attributes_name: 'cn'
gitlab_ldap_attributes_first_name: 'givenName'
gitlab_ldap_attributes_last_name: 'sn'
gitlab_ldap_lowercase_usernames: false

gitlab_smtp_enable: true
gitlab_smtp_address: mail.backslashseven.com
gitlab_smtp_port: 587
gitlab_smtp_user: nils@klackwerk.de
gitlab_smtp_password: "{{ vault_gitlab_smtp_password }}"
gitlab_smtp_domain: klackwerk.de
gitlab_smtp_authentication: login
gitlab_smtp_enable_starttls_auto: true
gitlab_smtp_tls: false
gitlab_smtp_pool: false

gitlab_email_from: nils@klackwerk.de
gitlab_email_display_name: GitLab
gitlab_email_reply_to: noreply@klackwerk.de
gitlab_email_subject_suffix: '[DEV]'

# This will create a cron job for weekly container registry cleanup without downtime
gitlab_container_registry_garbage_collect: true
# Cron timer for registry cleanup, defaulting to sunday 2 am
gitlab_container_registry_garbage_collect_minute: 0
gitlab_container_registry_garbage_collect_hour: 2
gitlab_container_registry_garbage_collect_weekday: 2

# Application settings
# you can add every parameter found in the official documentation to the dict
# https://docs.gitlab.com/ee/api/settings.html#list-of-settings-that-can-be-accessed-via-api-calls
gitlab_application_settings:
  # Set min key lenths, -1 disables the key type
  - param: 'rsa_key_restriction'
    value: -1
  - param: 'dsa_key_restriction'
    value: -1
  - param: 'ecdsa_key_restriction'
    value: 0
  - param: 'ecdsa_sk_key_restriction'
    value: 0
  - param: 'ed25519_key_restriction'
    value: 0
  - param: 'ed25519_sk_key_restriction'
    value: 0
# Set wether or not a user should need to be accepted by an admin after signup
  - param: 'require_admin_approval_after_user_signup'
    value: true
  - param: 'signup_enabled'
    value: true

vault_gitlab_smtp_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32326533616263626631383632393566653639343365626539646231346438383539323337663639
          3031633064653235366661303961386336386662646233320a306139663639666564653731613862
          66373164353966646236303338623836643862633563393931663438353637306265336639623639
          6131376339343439610a616232313232333537383463326366323461393739653762346566393563
          3837