- name: configure gitlab.rb
  template:
    src: templates/gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - reconfigure gitlab

- name: create container registry garbage collection cron job
  ansible.builtin.cron:
    name: "GitLab Container registry garbage collection"
    user: root
    minute: "{{ gitlab_container_registry_garbage_collect_minute }}"
    hour: "{{ gitlab_container_registry_garbage_collect_hour}}"
    weekday: "{{ gitlab_container_registry_garbage_collect_weekday }}"
    job: "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin gitlab-ctl registry-garbage-collect"
    cron_file: registry-garbage-collect
    state: present
  when: gitlab_container_registry_garbage_collect is true

- name: delete container registry garbage collection cron job
  ansible.builtin.cron:
    cron_file: registry-garbage-collect
    state: absent
  when: gitlab_container_registry_garbage_collect is false

- name: create gitaly backup cron job
  ansible.builtin.cron:
    name: "GitLab Gitlay Backup cron job"
    user: root
    minute: "{{ gitlab_backup_cron_minute }}"
    hour: "{{ gitlab_backup_cron_hour }}"
    weekday: "{{ gitlab_backup_cron_weekday }}"
    job: "/opt/gitlab/bin/gitlab-backup create CRON=1"
    cron_file: gitaly-backup
    state: present
  when: gitlab_backup_cron_enabled is true

- name: delete gitaly backup cron job
  ansible.builtin.cron:
    cron_file: gitaly-backup
    state: absent
  when: gitlab_backup_cron_enabled is false