- import_tasks: prerequisites.yml

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check if gitlab-ee is installed
  ansible.builtin.set_fact:
    gitlab_installed: true
  when: "'gitlab-ee' in ansible_facts.packages"

- import_tasks: setup.yml
  when: gitlab_installed is not defined

- import_tasks: configure.yml

# These tasks need a valid gitlab_access_token with api privileges,
# see http://gitlab.example.com/-/profile/personal_access_tokens
- import_tasks: configure_api.yml
  when: gitlab_installed is defined and gitlab_access_token is defined and gitlab_access_token != ''