---
- name: Create config directory
  ansible.builtin.file:
    owner: root
    group: root
    path: /etc/gitlab-runner
    state: directory

- name: Copy entrypoint.sh
  ansible.builtin.template:
    dest: /etc/gitlab-runner/entrypoint.sh
    src: templates/entrypoint.sh.j2
    owner: root
    group: root
    mode: '0700'

- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install docker-py
  ansible.builtin.pip:
    name: docker
    state: present

- name: Start GitLab Runner
  community.docker.docker_container:
    name: "runner-{{ gitlab_runner_name }}"
    image: "gitlab/gitlab-runner"
    state: 'started'
    command: "run --user=gitlab-runner --working-directory=/home/gitlab-runner"
    entrypoint: '/etc/gitlab-runner/entrypoint.sh'
    volumes:
      - /etc/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock