- hosts: all
  roles:
    - role: common
    - role: timezone
    - role: ufw

- hosts: gitlab
  roles:
    - role: gitlab

- hosts: gitlab_runner
  roles:
    - role: docker
    - role: gitlab_runner