ufw_default_incoming_policy: deny
ufw_default_outgoing_policy: allow
ufw_logging: 'off'

ufw_rules:
  - rule: allow
    interface: "{{ ansible_default_ipv4['interface'] }}"
    to_port: 22
    protocol: tcp