- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- name: packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - perl