- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == "Debian"

- name: yum update all
  dnf:
    state: latest
    name: '*'
  when: ansible_os_family == "RedHat"

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"