---
gitlab_external_url: 'http://gitlab.example.com'

gitlab_smtp_enable: false
gitlab_smtp_address: smtp.example.com
gitlab_smtp_port: 587
gitlab_smtp_user: smtp_user
gitlab_smtp_password: smtp_password
gitlab_smtp_domain: example.com
gitlab_smtp_authentication: login
gitlab_smtp_enable_starttls_auto: true
gitlab_smtp_tls: false
gitlab_smtp_pool: false

gitlab_email_from: gitlab@example.com
gitlab_email_display_name: Example
gitlab_email_reply_to: noreply@example.com
gitlab_email_subject_suffix:

gitlab_initial_root_password: 'yoursecurepasshere'



